version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@0.0.10. # Invoke the Heroku orb


jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./tests/mocked_unit_tests.py && python ./tests/unmocked_unit_tests.py
          name: Chat Test

workflows:
  main:
    jobs:
      - build-and-test
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter